name: Subida a firebase hosting:produccion

on:
  workflow_run:
    workflows: ["Pruebas"]
    branches: [master]
    types: 
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: generate # will run `yarn generate` command
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:produccion
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}